version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./:/var/www/Freshdesk
    depends_on:
      - php

  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./:/var/www/Freshdesk
    command: /bin/sh -c "docker-php-ext-install mysqli pdo pdo_mysql && php-fpm"


  composer:
    image: composer
    volumes:
      - ./:/var/www/Freshdesk
    working_dir: /var/www/Freshdesk
    command: install --ignore-platform-reqs