version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./:/var/www/Freshdesk
    depends_on:
      - php

  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./:/var/www/Freshdesk
    command: /bin/sh -c "apk add --no-cache $PHPIZE_DEPS \
      && apk add --no-cache autoconf g++ make \
      && pecl install xdebug-2.9.8 \
      && docker-php-ext-enable xdebug \
      && docker-php-ext-install mysqli pdo pdo_mysql \
      && echo 'zend_extension=xdebug.so' >> /usr/local/etc/php/php.ini \
      && echo 'xdebug.mode=debug' >> /usr/local/etc/php/php.ini \
      && echo 'xdebug.start_with_request=yes' >> /usr/local/etc/php/php.ini \
      && echo 'xdebug.client_host=host.docker.internal' >> /usr/local/etc/php/php.ini \
      && php-fpm"

  composer:
    image: composer
    volumes:
      - ./:/var/www/Freshdesk
    working_dir: /var/www/Freshdesk
    command: install --ignore-platform-reqs